version: 0.3

env:
  variables:
    # This S3 stores the ECS Reference Architecture CloudFormation templates
    # so that they can be deployed via a button on the project GitHub README
    #Modified for TechTestApp jnorback-open1
    S3_BUCKET: "jnorback-open1/ecs-refarch-cloudformation"

phases:

  pre_build: 
    commands:

      # Validate all of the CloudFormation templates
      - chmod a+x ./tests/validate-templates.sh
      - ./tests/validate-templates.sh

  build:
    commands:

      # Sync the templates
      # - aws s3 sync . s3://${S3_BUCKET}

