Description:  >
    This template deploys a Postgres DB spread across multiple
    Availability Zones

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    DBInstanceClass:
        Description: Which DB instance type should we use to build the AWS RDS?
        Type: String
        Default: db.t2.micro

    MyDBSubnets:
        Description: "Subnets to launch RDS DBs into"
        Type: "List<AWS::EC2::Subnet::Id>"

    #We are only using one security group for this so no list
    DatabaseSecurityGroup:
        Description: DataBase Security Group the DB should use.
        Type: AWS::EC2::SecurityGroup::Id

    DBMasterUsername:
        Description: the user used to connect to the database server
        Type: String
        Default: postgres

    DBMasterUserPassword:
        Description: the password used to connect to the database server
        Type: String
        Default: changeme

    DBName:
        Description: name of the database to use on the database server
        Type: String
        Default: app

    DBPort:
        Description: port to connect to the database server on
        Type: String
        Default: 5432

    DbHost:
        Description: host to connect to, ip or dns entry
        Type: String
        Default: localhost

    ListenHost:
        Description: listener configuration for the application, 0.0.0.0 for all IP, or specify ip to listen on
        Type: String
        Default: localhost

    ListenPort:
        Description: port to bind on the local server
        Type: String
        Default: 3000

Resources:
    MyDB:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: '100'
        BackupRetentionPeriod: '5'
        DBInstanceClass: db.t2.micro
        DBSubnetGroupName: !Ref MyDBSubnetGroup
        Engine: Postgres
        #Iops: '1000'
        MasterUsername: !Ref DBMasterUsername
        MasterUserPassword: !Ref DBMasterUserPassword
        MultiAZ: 'true'
        Port:  !Ref DbPort
        StorageType: 'gp2'
        Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-Postgres-DB
        VPCSecurityGroups: 
                - !Ref DatabaseSecurityGroup
        #EngineVersion: String
        #LicenseModel: String
        #OptionGroupName: String
        #PreferredBackupWindow: String
        #PreferredMaintenanceWindow: String

    MyDBSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: !Sub "${EnvironmentName} RDS DB subnet group"
        SubnetIds: !Ref MyDBSubnets
        Tags:
            - Key: Name
              Value: !Sub ${EnvironmentName} DbSubnetGroup

Outputs:
    InstanceID:
      Description: "RDS Database Instance ID"
      Value: !Ref MyDB

    RdsDbURL:
      Description: "RDS Database URL"
      Value: !GetAtt "MyDB.Endpoint.Address"

    VTT_DBUSER:
      Description: "the user used to connect to the database server"
      Value: !Ref DBMasterUsername

    VTT_DBPASSWORD:
      Description: "the password used to connect to the database server"
      Value: !Ref DBMasterUserPassword

    VTT_DBNAME:
      Description: "name of the database to use on the database server"
      Value: !Ref DBName

    VTT_DBPORT:
      Description: "port to connect to the database server on"
      Value:  !GetAtt "MyDB.Endpoint.Port"

    VTT_DBHOST:
      Description: "host to connect to, ip or dns entry"
      Value: !GetAtt "MyDB.Endpoint.Address"
      #VTT_DBHOST=localhost

    VTT_LISTENHOST:
      Description: "listener configuration for the application, 0.0.0.0 for all IP, or specify ip to listen on"
      Value: 0.0.0.0

    VTT_LISTENPORT:
      Description: "port to bind on the local server"
      DBPORTValue: 3000

