Description:  >
    This template deploys a Postgres DB spread across multiple
    Availability Zones 

Parameters:
    
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    
    DBInstanceClass:
        Description: Which DB instance type should we use to build the AWS RDS?
        Type: String
        Default: db.t2.micro

    DBSubnetGroupName: 
        Description: The Subnet Group Name for the subnets this Multi-AZ AWS RDS belongs to.
        Type: String

    DBSubnets:
        Description: "Subnets to launch RDS DBs into"
        Type: "List<AWS::EC2::Subnet::Id>"

    DatabaseSecurityGroup:
        Description: DataBase Security Group the DB should use.
        Type: String

    MasterUsername:
        Description: Allows one to set the DB master user name for the DB elsewhere
        Type: String
        Default: MyName
    
    MasterUserPassword:
        Description: Allows one to set the DB master user name password for the DB elsewhere
        Type: String
        Default: MyPassword
    


Resources:
    MyDB:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: '20'
        BackupRetentionPeriod: '5'
        DBInstanceClass: db.t2.micro
        DBSubnetGroupName: !Ref DbSubnetGroup
        Engine: PostgreSQL
        #Iops: '1000'
        MasterUsername: MyName
        MasterUserPassword: MyPassword
        MultiAZ: 'true'
        Port:  '5432'
        StorageType: 'gp2'
        Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-Postgres-DB
        VPCSecurityGroups: 
        - !Ref DatabaseSecurityGroup
        #EngineVersion: String
        #LicenseModel: String
        #OptionGroupName: String
        #PreferredBackupWindow: String
        #PreferredMaintenanceWindow: String
 
    DbSubnetGroup:
      Type: AWS::RDS::DBSubnetGroup
      Properties:
        DBSubnetGroupDescription: !Sub "${EnvironmentName} RDS DB subnet group"
        SubnetIds:
          Ref: "DBSubnets"
